### ISSUE TITLE
Inspired by warrick ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [sangaline/wayback-machine-scraper#11]
does [wayback-machine-scraper](https://github.com/sangaline/wayback-machine-scraper) want to be a replacement for [warrick](https://github.com/oduwsdl/warrick) ?

to what extent is it inspired or based on warrick ?
http://timetravel.mementoweb.org/

**Comment by sangaline** [comment]
It's not inspired or based on warrick at all, I had never seen that project until you posted it. Skimming through their README, warrick seems focused on recovering a site at a specific point in time. That behavior is possible with wayback-machine-scraper, but it's also possible to download multiple versions of a page, specify time ranges, and filter based on regular expressions. The core functionality of wayback-machine-scraper is also made accessible through the [scrapy-wayback-machine](scrapy-wayback-machine) Scrapy middleware, so it's easy to integrate into Python/Scrapy projects. I wouldn't say that wayback-machine-scraper is aiming to be a replacement for warrick or any other project, just that they're projects in similar problem domains with different interfaces and slightly different target use cases.
