### ISSUE TITLE
ImportError: cannot import name timezone

### ISSUE THREAD

**Issue by dannymichel** [sangaline/wayback-machine-scraper#2]
I tried pip install datetime and pip3 install datetime and am still getting the error.

**Comment by sangaline** [comment]
Do you get this error when installing it from pypi (*e.g.* `pip3 install wayback-machine-scraper`)? You shouldn't have to install any dependencies manually, but you will need to use `pip3` to install it if your default `pip` is tied to Python 2.

**Comment by sangaline** [comment]
Let me know if you're stilling still having this issue and I'll reopen it.
