### ISSUE TITLE
How can I use this to get the number of times a site is crawled by the wayback?

### ISSUE THREAD

**Issue by khantoocool** [sangaline/wayback-machine-scraper#3]
As shown here, the number of times, it was crawled.
[https://web.archive.org/web/*/panda.com](url)

**Comment by sangaline** [comment]
You can do this by querying the CDX server directly. For example,

```bash
URL=panda.com
curl "http://web.archive.org/cdx/search/cdx?url=${URL}&fl=statuscode" | grep 200 | wc -l
```

will tell you that panda.com has been scraped with a 200 response code 589 times. The `fl=statuscode` querystrying is telling the server to just return the response status codes for crawls, the `grep 200` is removing status codes other than 200, and `wc -l` counts the number of lines/crawls.

**Comment by khantoocool** [comment]
I am windows, How can I do that from here?

**Comment by khantoocool** [comment]
Thanks, I did it in windows though, in Java with a for loop to count how many times :)
