### ISSUE TITLE
Error with setup

### ISSUE THREAD

**Issue by mrme44** [sangaline/wayback-machine-scraper#6]
when I run `pip install wayback-machine-scraper`

I get the error

`error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158`

Is it possible for you to include a pre-built wheel file, so we don't have to compile this project ourselves.

**Comment by sangaline** [comment]
Sounds like @geajack's solution works for people on Windows.
